version: "3"

services:
  gitea:
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    hostname: gitea
    ports:
      - 4000:3000 #webgui
      - 2222:22 #ssh
    image: gitea/gitea:latest
    restart: unless-stopped
    volumes:
      - /home/bryan/selfhosted/docker/gitea/data:/data
